### ISSUE TITLE
What is the status of this package?

### ISSUE THREAD

**Issue by jlozano** [dvyukov/go-fuzz#128]
@dvyukov This is an awesome package! But, it looks like it needs some updates to work with recent changes to the go library, e.g `golang.org/x/tools/go/types` -> `go/types` are there plans to support this on your end? Mind if I take a hack at it myself?

Thank you for any information and a really cool tool!

**Comment by dvyukov** [comment]
@jlozano It would be great if you can update to go/types.
There are several related issues: #101 and #126

**Comment by paultag** [comment]
@dvyukov I started down this, but it's a bit of a rats nest, the modules were changed when they were absorbed into the stdlib -- some notes:

  - `go/exact` became `go/constant`. Importing `exact "go/constant"` seems fine (or fixing them all).
  - `go/types` is messy, because `types.Config` lost the `Packages` member (in commit e5b76747c9f30a736c38137ad7f5939c02b3e285), which was because it got spun out into `go/importer`

Just trying to patch it until it worked backfired and introduced a few regressions because I am horrendously jet lagged and have what amounts to overcooked noodles for brains at the moment.

**Comment by dvyukov** [comment]
@paultag, thanks for looking into this!

@griesemer How do we manage without go/types.Config.Packages now? Here is what we did before:
https://github.com/dvyukov/go-fuzz/blob/master/go-fuzz-build/main.go#L325

**Comment by griesemer** [comment]
@dvyukov go/types doesn't really need to know about already imported packages. It's all in the importer. Probably need to provide a closure that matches the importer API and that tracks the already seen packages (haven't looked at your code in detail). It should be pretty straight-forward. You can look at Go std lib api checker, for instance.
