### ISSUE TITLE
Send binary from coordinator to workers

### ISSUE THREAD

**Issue by AlekSi** [dvyukov/go-fuzz#181]
When using go-fuzz in distributed mode, one has to copy binary (`.zip` archive) to all worker nodes with a separate tool. It would be nice to make coordinator send it to connected workers.

**Comment by dvyukov** [comment]
I think this needs to be discussed in the context of the upstream proposal at this point. I don't want to do any more significant work on go-fuzz at this point.
Note: the upstream proposal does not contain any explicit support for complex distributed setups. And I think it was somewhat premature to include it directly into go-fuzz as well. A better way is to build a single-machine fuzzing in such way so that it allows building more complex automation on top of it.
The plan is to integrate the upstream fuzzing with OSS-Fuzz, which should ensure that such higher-level automation is possible.

**Comment by AlekSi** [comment]
Ok, then I'm interested in working on a distributed version myself if an integrated version will provide the required support. /cc @andybons

**Comment by dvyukov** [comment]
You are more than welcome to do so.
You can check the interface in the proposal. The model was taken from OSS-Fuzz which copies, merges and minimizes corpus itself. Obviously you can copy binaries without their direct support for that. On top of that the system may need to be able to wind up VMs on a cloud hosting, or maybe support dynamic registration of worker machines.

**Comment by AlekSi** [comment]
> The model was taken from OSS-Fuzz which copies, merges and minimizes corpus itself.

Then it means there is no work for the coordinator to distribute? So it only should send binaries, and receive and persist new corpus data and crashes?

**Comment by dvyukov** [comment]
More or less, yes. It also needs to send corpus, minimize corpus, dedup crashes and maybe something else.
