### ISSUE TITLE
How to persist some common objects during every Fuzz() executing?

### ISSUE THREAD

**Issue by Cipher731** [dvyukov/go-fuzz#255]
There's a situation that I need to initialize some network mock services for feed the fuzz input to the actual to-test functions. It will be expensive to create such service objects in every Fuzz() running. Is there a way to persist such objects and make them available during every Fuzz() executing to improve the efficiency?

**Comment by josharian** [comment]
Can you make them global and initialize them in an init function?

**Comment by Cipher731** [comment]
I didn't realize that. This might work. Thank you.

**Comment by tolgahanakgun** [comment]
Hii,

I also have this problem and could not figure out how to solve it! The Init function is not invoked once!
I am trying to test WireGuard Go implementation. The code creates a virtual network interface. So, I  shouldn't run the whole code for each test cases for both performance and the state of the network interface issues. However, Go-fuzz runs the whole code instead of running just the Fuzz function. My WireGuard code is  complex. So, I am using a simple example.
Simple example:

```
package fuzzing

import (
    "fmt"
    "os"
    "time"
)

var executed = false

func donNotRun() {
    executed = true
    f, err := os.OpenFile("text.test", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
    if err != nil {
        fmt.Println(err)
    }

    defer f.Close()
    if _, err := f.WriteString(time.Now().Format("2006-01-02 15:04:05")+"\n"); err != nil {
        fmt.Println(err)
    }
}

func Fuzz(data []byte) int{
    if !executed{
        donNotRun()
    }
    return 0
}
```
I build and run this file. Fort the safety of the variable, I used parallelism level 1.


```
osboxes@osboxes:~/Desktop/test-go$ ./go-fuzz-build
osboxes@osboxes:~/Desktop/test-go$ ./go-fuzz -procs=1
2019/11/20 19:51:53 workers: 1, corpus: 3 (3s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 0, uptime: 3s
2019/11/20 19:51:56 workers: 1, corpus: 3 (6s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 147, uptime: 6s
2019/11/20 19:51:59 workers: 1, corpus: 3 (9s ago), crashers: 0, restarts: 1/6698, execs: 26793 (2977/sec), cover: 147, uptime: 9s
```

I expect to see only one line in the test.text file. However, there are multiple lines in the file. Also, I tried the same code with init() function (removed the executed flag and renamed doNotRun to init). The result is the same. The init() function is invoked multiple times.
```
2019-11-20 19:51:50
2019-11-20 19:51:50
2019-11-20 19:51:51
2019-11-20 19:51:53
2019-11-20 19:51:53
2019-11-20 19:51:55
2019-11-20 19:51:57
2019-11-20 19:51:58
2019-11-20 19:51:59
2019-11-20 19:51:59
```

**Comment by josharian** [comment]
Even with one worker, the binary may get re-executed multiple times. But code in an init function (or protected by a sync.Once) really should only once for any given binary execution. If you need code to only be executed once per fuzzing session, you’ll have to use some external resource (file lock, DB, etc).

**Comment by tolgahanakgun** [comment]
This code also creates multiple lines in the text.test file.
```
package fuzzing

import (
    "fmt"
    "os"
    "time"
)

func init() {
    f, err := os.OpenFile("text.test", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
    if err != nil {
        fmt.Println(err)
    }

    defer f.Close()
    if _, err := f.WriteString(time.Now().Format("2006-01-02 15:04:05")+"\n"); err != nil {
        fmt.Println(err)
    }
}

func Fuzz(data []byte) int{
    return 0
}

```
I cannot use simply other resources because the code holds the network interface state, listeners for the socket, private and public keys, session keys for the encryption. I will also try with sync.once.
