### ISSUE TITLE
line numbers are wrong in crasher output

### ISSUE THREAD

**Issue by joeshaw** [dvyukov/go-fuzz#32]
The fuzzed data caused a panic, and reported a stack trace.  When I looked at the output, the line number made no sense.  (It was the closing brace of a `if err != nil { ... }` block)

I only noticed when I ran `go-fuzz-build` with `-workdir` that the code is instrumented before building, which throws off line numbers.  The `//line` directive would be helpful in mapping the code to the original line numbers.

**Comment by dvyukov** [comment]
Thanks!

I have a plan for a more fundamental fix. Which is to build a non-instrumented binary (this already happens anyway) and include it into output archive. Then use that binary for one final execution of crashing inputs. This will provide correct line numbers, correct file names, ensure that the issue is not with instrumentation, ensure that the issue is not a spurious failure and also update output to match final minimized input (currently output is from non-minimized input which is also confusing).
But that will be more work.

**Comment by joeshaw** [comment]
:+1: sounds good.  Thanks for merging this in the meantime.
