### ISSUE TITLE
cover.go:41: missing function body

### ISSUE THREAD

**Issue by brunoqc** [dvyukov/go-fuzz#36]
I have this problem on Linux but not on Windows.

```sh
go get github.com/dvyukov/go-fuzz/go-fuzz
# github.com/dvyukov/go-fuzz/go-fuzz
GOPATH/src/github.com/dvyukov/go-fuzz/go-fuzz/cover.go:41: missing function body
```

go version go1.4.2 linux/386

**Comment by dvyukov** [comment]
That's because there is an assembly function implemented only for amd64 (64-bit mode). It is easy to fix, but I would suggest to switch to 64-bits on windows. Go-fuzz can easily run out of memory on 32-bits and the non-assembly implementation will be slower.
Is there any particular reason you use 32-bits on windows?

**Comment by brunoqc** [comment]
> Is there any particular reason you use 32-bits on windows?

I have the problem on 32-bits Linux. I can't use 64-bits Linux at work.

I have 64-bits Windows. I'll use it.

Thanks.

**Comment by dvyukov** [comment]
Thanks
Let's keep this open. It probably needs to be fixed still.
